[package]
name = "airdrop_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5.0"
borsh = "0.10.3"
solana-sdk = "1.16.0"
solana-client = "1.16.0"
solana-program = "1.16.0"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
